inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 18
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 6

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  AllowPredicates: true