title: syncopated notes
include:
  - "_pages"
  - "_posts"
  - "_projects"
  - "_pages/*.html"
  - "notebook/"
  - "_media/"
  - "_assets/"
  - "_notes/"
exclude:
  - "plugins/"
  - "websitestuff/"
email: rwpannick@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A specified selection of tokens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://b08x.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  b08x

# Build settings
plugins:
  - jekyll-last-modified-at
  - jekyll-jupyter-notebook
  - jekyll_asciinema
  - jekyll-spaceship
  - jekyll_picture_tag
  - jekyll-toc
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-pandoc

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink: pretty
relative_permalinks: false

sass:
  sass_dir: _sass
  style: compressed

defaults:
  # - scope:
  #     path: "**/*"
  #   values:
  #     layout: "page"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "pagev2"

jekyll-spaceship:
  mermaid-processor:
    css:
      class: "mermaid!"
    config:
      theme: dark

picture:
  source: "assets/img"
  output: "assets/img/generated"
  suppress_warnings: true
  nomarkdown: false

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-


# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: false
  collection: 'posts'


collections:
  notes:
    output: true
    permalink: /:slugified_categories/:title
  posts:
    output: true
    permalink: /:slugified_categories/:title
    
############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true
  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: true       # Whether to replace all uppercase letters with their lowercase counterparts
    enabled: true
  # Collection pages, omit to disable
  collections:
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    silent: false
    slugify:
      mode: 'ascii'   # :coll is slugified.
      case: true
    enabled: true
  # Tag pages, omit to disable
  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: true
    enabled: true

# feed:
#   collections:
#     notes:
#       path: "/feed.atom"
