#!/usr/bin/env ruby
# frozen_string_literal: true

# Copy documentation out of a source repository into a _docs collection,
# injecting Jekyll frontmatter and rewriting intra-repo links.
#
#   ruby _sync/sync_docs.rb _sync/ris-assist.yml
#   ruby _sync/sync_docs.rb _sync/ris-assist.yml --check
#
# --check writes nothing and exits non-zero if any output is missing or stale,
# which makes it usable as a pre-commit or CI guard.
#
# Generated files carry a do-not-edit banner. Edit the upstream source and
# re-run; hand edits are overwritten without warning.

require 'yaml'
require 'fileutils'
require 'digest'

class DocSync
  BANNER = 'Generated by _sync/sync_docs.rb — do not edit. ' \
           'Edit the source file in the plugin repo and re-run the sync.'

  def initialize(manifest_path, check_only: false)
    @manifest_path = manifest_path
    @check_only = check_only
    @manifest = YAML.safe_load_file(manifest_path)
    @site_root = File.expand_path('..', __dir__)
    @repo_root = File.expand_path(@manifest.fetch('repo_root'), @site_root)
    @output_dir = File.join(@site_root, @manifest.fetch('output_dir'))
    @doc_set = @manifest.fetch('doc_set')
    @pages = @manifest.fetch('pages')
    @written = []
    @stale = []
    @missing_sources = []
  end

  def run
    abort "Source repo not found: #{@repo_root}" unless Dir.exist?(@repo_root)
    FileUtils.mkdir_p(@output_dir) unless @check_only

    @pages.each_with_index { |page, index| process(page, index) }
    report
  end

  private

  # Slug -> permalink, so intra-repo links between synced files resolve to
  # site URLs rather than dangling at GitHub paths.
  def link_map
    @link_map ||= @pages.each_with_object({}) do |page, map|
      map[page.fetch('source')] = permalink(page.fetch('slug'))
      map[File.basename(page.fetch('source'))] = permalink(page.fetch('slug'))
    end
  end

  def permalink(slug)
    "/docs/#{@doc_set}/#{slug}/"
  end

  def process(page, index)
    source = File.join(@repo_root, page.fetch('source'))
    unless File.exist?(source)
      @missing_sources << page.fetch('source')
      return
    end

    body = File.read(source)
    body = strip_leading_h1(body)
    body = rewrite_links(body, page.fetch('source'))

    rendered = frontmatter(page, index) + "\n" + body.strip + "\n"
    target = File.join(@output_dir, "#{page.fetch('slug')}.md")

    if @check_only
      @stale << page.fetch('slug') unless current?(target, rendered)
      return
    end

    unless current?(target, rendered)
      File.write(target, rendered)
      @written << page.fetch('slug')
    end
  end

  def current?(target, rendered)
    File.exist?(target) && File.read(target) == rendered
  end

  # The layout renders page.title as an <h1>, so a leading H1 in the source
  # would double it.
  def strip_leading_h1(body)
    body.sub(/\A\s*#\s+.*?(\n|\z)/, '')
  end

  # Links between synced pages become site URLs. Links to repo files that are
  # NOT published fall back to the source repo on GitHub, so an unpublished
  # target degrades to a working external link instead of a dead relative one.
  def rewrite_links(body, source_rel)
    blob_base = @manifest['github_blob_base']
    source_dir = File.dirname(source_rel)

    body.gsub(%r{\]\(([^)\s]+\.md)(\#[^)\s]*)?\)}) do
      path = Regexp.last_match(1)
      anchor = Regexp.last_match(2)
      whole = Regexp.last_match(0)

      mapped = link_map[path] || link_map[File.basename(path)]
      next "](#{mapped}#{anchor})" if mapped
      next whole unless blob_base

      resolved = File.expand_path(path, "/#{source_dir}").sub(%r{\A/}, '')
      "](#{blob_base.chomp('/')}/#{resolved}#{anchor})"
    end
  end

  def frontmatter(page, index)
    data = {
      'title' => page.fetch('title'),
      'description' => page['description'],
      'permalink' => permalink(page.fetch('slug')),
      'doc_set' => @doc_set,
      'source_path' => page.fetch('source'),
      'nav_order' => page['nav_order'],
      'toc' => true
    }.compact

    prev_page = @pages[index - 1] if index.positive?
    next_page = @pages[index + 1]
    data['prev'] = pager(prev_page) if prev_page
    data['next'] = pager(next_page) if next_page

    "---\n# #{BANNER}\n" + data.to_yaml.sub(/\A---\n/, '') + "---\n"
  end

  def pager(page)
    { 'title' => page.fetch('title'), 'url' => permalink(page.fetch('slug')) }
  end

  def report
    unless @missing_sources.empty?
      warn "Missing sources (#{@missing_sources.size}):"
      @missing_sources.each { |path| warn "  - #{path}" }
    end

    if @check_only
      if @stale.empty? && @missing_sources.empty?
        puts "up to date (#{@pages.size} pages)"
        exit 0
      end
      warn "stale: #{@stale.join(', ')}" unless @stale.empty?
      exit 1
    end

    if @written.empty?
      puts "up to date (#{@pages.size} pages, nothing changed)"
    else
      puts "wrote #{@written.size} of #{@pages.size}: #{@written.join(', ')}"
    end
    exit(@missing_sources.empty? ? 0 : 1)
  end
end

manifest = ARGV.find { |arg| !arg.start_with?('--') }
abort 'usage: ruby _sync/sync_docs.rb <manifest.yml> [--check]' unless manifest

DocSync.new(manifest, check_only: ARGV.include?('--check')).run
