import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticPlaceholder } from '../../main';

/**
 * Epic 4: Hydration Mismatch Prevention Test Suite
 * 
 * This suite ensures that the React StaticPlaceholder (used as Suspense fallback)
 * perfectly mirrors the raw HTML generated by Jekyll's _includes/island.html.
 */

describe('Hydration Mismatch Prevention', () => {
  
  // This mirrors the default placeholder logic in _includes/island.html
  const getJekyllPlaceholder = (componentName: string, content: string = '') => {
    const defaultContent = `
      <div class="animate-pulse bg-surface border border-border rounded-lg p-4 text-center">
        <span class="text-muted font-mono text-sm">LOADING_${componentName.toUpperCase()}...</span>
      </div>
    `.trim().replace(/>\s+</g, '><'); // Simple whitespace normalization

    const finalContent = content || defaultContent;
    
    return `<div class="island-placeholder" data-island-status="loading">${finalContent}</div>`;
  };

  test('StaticPlaceholder mirrors SearchCmdK default Jekyll output', () => {
    const componentName = 'SearchCmdK';
    const jekyllHTML = getJekyllPlaceholder(componentName);
    
    // In our implementation, StaticPlaceholder is passed the innerHTML of the container's placeholder div
    const innerHTML = `
      <div class="animate-pulse bg-surface border border-border rounded-lg p-4 text-center">
        <span class="text-muted font-mono text-sm">LOADING_${componentName.toUpperCase()}...</span>
      </div>
    `.trim().replace(/>\s+</g, '><');

    const reactOutput = renderToString(<StaticPlaceholder html={innerHTML} />);
    
    // The reactOutput will be the wrapper div + the innerHTML
    expect(reactOutput).toContain('class="island-placeholder"');
    expect(reactOutput).toContain('data-island-status="loading"');
    expect(reactOutput).toContain(innerHTML);
    
    // Strict structural check (ignoring React-specific attributes like data-reactroot if present in older versions)
    // React 19 renderToString produces clean HTML.
    expect(reactOutput).toBe(jekyllHTML);
  });

  test('StaticPlaceholder mirrors custom placeholder for GraphView', () => {
    const customContent = `
      <div class="w-full h-96 bg-surface animate-pulse flex items-center justify-center border border-border rounded-lg">
        <span class="text-muted font-mono">STATIC HTML PLACEHOLDER (Waiting for React...)</span>
      </div>
    `.trim().replace(/>\s+</g, '><');

    const jekyllHTML = getJekyllPlaceholder('GraphView', customContent);
    const reactOutput = renderToString(<StaticPlaceholder html={customContent} />);
    
    expect(reactOutput).toBe(jekyllHTML);
  });

  test('Whitespace consistency check', () => {
    // This test detects if Jekyll's 'strip' filter and React's rendering diverge
    const input = '  <div>  Content  </div>  ';
    const stripped = input.trim();
    
    const reactOutput = renderToString(<StaticPlaceholder html={stripped} />);
    
    // React doesn't add whitespace inside dangerouslySetInnerHTML
    expect(reactOutput).toBe(`<div class="island-placeholder" data-island-status="loading">${stripped}</div>`);
  });
});
